# Generated by Django 4.1.1 on 2022-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(help_text='Имя женщины', max_length=250),
        ),
    ]
